### ISSUE TITLE
supabase-js@2.42.5 breaks client auth with edge functions

### ISSUE THREAD

**Issue by b-snel** [supabase/supabase-js#1022]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When I get the authorization header from the client in an edge function I'm unable to make a supabase client with the newest version of supabase-js (using deno edge functions). The behavior doesn't happen on 2.42.4 and below. I have rolled back but I wanted to bring this to your attention.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## Expected behavior

Able to get user auth details. See code snippet at bottom of how I typically do that.

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context

`import { corsHeaders } from '../_shared/cors.ts'
import { createClient } from "supabase-js"
import { createSupabaseClient } from '../_shared/supabaseClient.ts'

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  const authHeader = req.headers.get('Authorization')!
  const supabaseClient = createSupabaseClient(authHeader)

  // Get the session or user object
  const { data } = await supabaseClient.auth.getUser()
  const user = data.user

  if (!user) {
    throw new Error('User is null');
  }

}`

and here is the definition for my client function:
`import { createClient, SupabaseClient } from "supabase-js"

export function createSupabaseClient(authHeader: string): SupabaseClient {
  return createClient(
    Deno.env.get('SUPABASE_URL') ?? '',
    Deno.env.get('SUPABASE_ANON_KEY') ?? '',
    { global: { headers: { Authorization: authHeader } } }
  );
}`

**Comment by darrendawson** [comment]
I ran into this today as well when I deployed a new version of an existing edge function and immediately started getting Auth errors.

```
AuthSessionMissingError: Auth session missing!
    at https://esm.sh/v135/@supabase/auth-js@2.63.1/deno/auth-js.mjs:2:29428
    at _._useSession (https://esm.sh/v135/@supabase/auth-js@2.63.1/deno/auth-js.mjs:2:27511)
    at eventLoopTick (ext:core/01_core.js:64:7)
    at async _._getUser (https://esm.sh/v135/@supabase/auth-js@2.63.1/deno/auth-js.mjs:2:29101)
    at async https://esm.sh/v135/@supabase/auth-js@2.63.1/deno/auth-js.mjs:2:28964
    at async https://esm.sh/v135/@supabase/auth-js@2.63.1/deno/auth-js.mjs:2:26791 {
  __isAuthError: true,
  name: "AuthSessionMissingError",
  status: 400,
  code: undefined
}
```

**Comment by zguo123** [comment]
Looks like it's affecting me as well. 


```
AuthSessionMissingError: Auth session missing!
    at https://esm.sh/v135/@supabase/auth-js@2.63.1/esnext/auth-js.mjs:2:29430
    at _._useSession (https://esm.sh/v135/@supabase/auth-js@2.63.1/esnext/auth-js.mjs:2:27513)
    at eventLoopTick (ext:core/01_core.js:64:7)
    at async _._getUser (https://esm.sh/v135/@supabase/auth-js@2.63.1/esnext/auth-js.mjs:2:29103)
    at async https://esm.sh/v135/@supabase/auth-js@2.63.1/esnext/auth-js.mjs:2:28966 {
  __isAuthError: true,
  name: "AuthSessionMissingError",
  status: 400,
  code: undefined
}
```

**Comment by CookedApps** [comment]
Wasted 4 hours debugging this... 🥲

**Comment by zguo123** [comment]
> Wasted 4 hours debugging this... 🥲

LMAO, you were not alone. I restarted the database, and I reset my jwt tokens lmao.

**Comment by andymitchell** [comment]
+1 

Observations: 
- Authentication is working through the gateway, as the served code of the Edge Function executes 
- But using SupabaseJS 2.42.5 in the Edge Function, to createClient and then getUser, returns empty 


<img width="786" alt="Screenshot 2024-04-19 at 19 50 35" src="https://github.com/supabase/supabase-js/assets/85046/e00bf041-7bd1-4e02-b688-0fbb7a26e7a3">

**Comment by christophemenager** [comment]
I confirm I have the same issue

**Comment by zguo123** [comment]
Here's the solution: 

- https://github.com/supabase/auth-js/pull/876

via Discord: 
> No
You have to strip the Bearer part out
You just want a jwt.
supabaseClient.auth.getUser(authHeader.split(' ')[1]);  Another user just posted this.  Not verified.

**Comment by j4w8n** [comment]
Here is my observation:

PR https://github.com/supabase/auth-js/pull/876 adds a check for `data.session?.access_token` inside of `getUser()`. If it doesn't exist, then processing stops and returns `null` - which is what devs are now seeing in edge functions, because there is no Supabase session at this point.

Previously, without the new PR code, it would have just made a fetch request to the auth backend using `_request`:
```js
/* https://github.com/supabase/auth-js/blob/v2.63.1/src/GoTrueClient.ts#L1182-L1185 */
return await _request(this.fetch, 'GET', `${this.url}/user`, {
  headers: this.headers,
  jwt: data.session?.access_token ?? undefined,
  xform: _userResponse,
})
```

And if you look at `_request`, it's taking the `jwt` value, if it exists, and sets the `Authorization` header - which means the auth backend looks at that header to grab the JWT, lookup the user, and return a user response. And even if `jwt` is `undefined`, it still passes any Supabase client headers. So by setting the Authorization header in the edge function's Supabase client, we were bypassing the need to pass-in the JWT to `getUser()` in order for this to work without a session.
```js
/* https://github.com/supabase/auth-js/blob/v2.63.1/src/lib/fetch.ts#L127-L143 */
export async function _request(
  fetcher: Fetch,
  method: RequestMethodType,
  url: string,
  options?: GotrueRequestOptions
) {
  const headers = {
    ...options?.headers,
  }

  if (!headers[API_VERSION_HEADER_NAME]) {
    headers[API_VERSION_HEADER_NAME] = API_VERSIONS['2024-01-01'].name
  }

  if (options?.jwt) {
    headers['Authorization'] = `Bearer ${options.jwt}`
  }
...
```

**Comment by ffaubert** [comment]
Seems like a pretty major change for such a minor version bump. This broke my app too.

**Comment by jareddr** [comment]
+1 This broke my app too. I was deploying new edge functions in dev today and thought I was having the worst coding day ever for an hour or two.  Because my edge functions don't have a pinned supabase library version the new code was getting picked up whenever I would deploy a new version of an edge function.

I'm sure many people like me have used the [supabase edge function auth docs](https://supabase.com/docs/guides/functions/auth) as a starting point for how to get authenticated user data within an edge function.  This suggests that you can leave the `getUser()` function empty and indeed it has been working that way for months prior.

I ended up having to go through every edge function and patch it like this
```
const supabaseClient = createClient(
	Deno.env.get('SUPABASE_URL') ?? '',
	Deno.env.get('SUPABASE_ANON_KEY') ?? '',
	{ global: { headers: { Authorization: req.headers.get('Authorization')! } } }
);
const JWT = req.headers.get('Authorization')?.split(' ')[1] || '';
const userData = await supabaseClient.auth.getUser(JWT);
```

I'm confused why the supabase client needs the same JWT twice.  I don't know all of the intended uses of the `getUser` function, but surely there should be some convenience function within the supabase client that will grab the user data matching the authorization header passed in when creating the client.

I think my take away here is to not do this in my edge function code
```
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
```
and instead do this
```
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.42.4';
```

and then only upgrading when I explicitly intend to move to a new version.

**Comment by GaryAustin1** [comment]
I'm going to move this to the auth repository as it seems to be the underlying auth-js release is the issue.
