### ISSUE TITLE
bad_jwt when auth.getUser 

### ISSUE THREAD

**Issue by FerranVidalB** [supabase/supabase-js#1196]
# Bug report

Created an Edge Function for user-self-deletion but when I create the supabaseClient and try to getUser(jwt) I recieve this error

code: "bad_jwt"
name: "AuthApiError"
status: 403
__isAuthError: true

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

```
import { serve } from 'https://deno.land/std@0.182.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.43.4'
import { corsHeaders } from '../_shared/cors.ts'

console.log(`Function "user-self-deletion" up and running!`)

serve(async (req: Request) => {
  // This is needed if you're planning to invoke your function from a browser.
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }
  try {
    const authorization = req.headers.get('Authorization');
    if (!authorization) { 
      return new Response(JSON.stringify({ error: "No authorization header passed" }), 
      { status: 500, headers: { 'Content-Type': 'application/json' }, }); 
    }

    // Create a Supabase client with the Auth context of the logged in user.
    const supabaseClient = createClient(
      // Supabase API URL - env var exported by default.
      Deno.env.get('SUPABASE_URL') ?? '',
      // Supabase API ANON KEY - env var exported by default.
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
      // Create client with Auth context of the user that called the function.
      // This way your row-level-security (RLS) policies are applied.
      { global: { headers: { Authorization: req.headers.get('Authorization')! } } }
    )


    // const user_id =await supabaseClient.auth.getUser(authorization)
    // Get JWT from auth header
    const jwt = authorization.replace("Bearer ", "");

    // Get the user object
    const {  data: { user },} = await supabaseClient.auth.getUser(jwt);
```
## Expected behavior
I want to know why I'm getting this error.

## System information
supabase@1.167.4

## Additional context

    I checked the SUPABASE_URL, ANON_KEY and they are ok. The jwt is not empty.

**Comment by Electronica-dev** [comment]
I have a very similar error. Did you manage to find out what was wrong?

**Comment by bruno-branco** [comment]
Any news here? I think I'm with the same problem

**Comment by h14h** [comment]
I'm running into the same issue. I also created a minimal reproduction of it here:
https://github.com/h14h/jwt-test

To get this reproduced, I followed created a scaffold Supabase React app per [these instructions](https://supabase.com/docs/guides/getting-started/quickstarts/reactjs), and then followed Supabase's official getting started guide for [Supabase Auth w/ Edge Functions](https://supabase.com/docs/guides/functions/auth) to a tee, and then added some logging to display what's happening.

I triple-checked that the correct bearer token was being sent and used.

Here's the produced error:
```
AuthApiError: invalid claim: missing sub claim
    at handleError (file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@supabase/auth-js/2.68.0/dist/main/lib/fetch.js:69:11)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async _handleRequest (file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@supabase/auth-js/2.68.0/dist/main/lib/fetch.js:114:9)
    at async _request (file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@supabase/auth-js/2.68.0/dist/main/lib/fetch.js:95:18)
    at async SupabaseAuthClient._getUser (file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@supabase/auth-js/2.68.0/dist/main/GoTrueClient.js:881:24)
    at async SupabaseAuthClient.getUser (file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@supabase/auth-js/2.68.0/dist/main/GoTrueClient.js:870:20)
    at async Object.handler (file:///Users/h14h/code/pro/jwt-test/supabase/functions/hello-jwt/index.ts:15:27)
    at async respond (ext:sb_core_main_js/js/http.js:197:14) {
  __isAuthError: true,
  name: "AuthApiError",
  status: 403,
  code: "bad_jwt"
}
```

My only conclusion is that either a) Supabase's documentation is incorrect, or b) there's a bug within Supabase Edge Functions.

I'd be happy to be proven wrong -- this is blocking progress on my current project and would love a resolution ASAP.

**Comment by peperoli** [comment]
I encountered this error when trying to use the service role key in a local Supabase environment, which doesn't seem possible at the moment.
