### ISSUE TITLE
Trouble with svelte/sapper template

### ISSUE THREAD

**Issue by voboda** [supabase/supabase-js#124]
# Sapper#rollup throws warnings on import 

Supabase is amazing, so thank you!

I'm trying to use it with svelte/sapper and running into some hiccups.  It seems there's some underlying problem with rollup and maybe ES versions, and in the end it runs but with a large number of warnings that clutter feedback in `npm run dev`.

## To Reproduce

1. Start with a fresh sapper template
``` 
npx degit sveltejs/template fresh
cd fresh 
npm i
```
2. Install supabase-js `npm i --save @supabase/supabase-js`
3. Import in `src/App.svelte`
```
	import { createClient } from '@supabase/supabase-js'
```
4. Run `npm run build` to see a rollup error suggesting @rollup/plugin-json
```> rollup -c


src/main.js → public/build/bundle.js...
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
node_modules/@supabase/supabase-js/dist/module/SupabaseClient.js
1: var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
                    ^
2:     function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
3:     return new (P || (P = Promise))(function (resolve, reject) {
...and 1 other occurrence
node_modules/@supabase/realtime-js/dist/module/RealtimeClient.js
1: var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
                    ^
2:     function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
3:     return new (P || (P = Promise))(function (resolve, reject) {
...and 1 other occurrence
node_modules/@supabase/gotrue-js/dist/module/GoTrueApi.js
1: var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
                    ^
2:     function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
3:     return new (P || (P = Promise))(function (resolve, reject) {
...and 1 other occurrence

...and 3 other files
[!] Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files)
node_modules/websocket/package.json (2:9)
1: {
2:   "_from": "websocket@^1.0.31",
            ^
3:   "_id": "websocket@1.0.33",
4:   "_inBundle": false,
Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files)
    at error (/repos/voboda/fresh-3/node_modules/rollup/dist/shared/rollup.js:4528:30)
    at Module.error (/repos/voboda/fresh-3/node_modules/rollup/dist/shared/rollup.js:9935:16)
    at tryParse (/repos/voboda/fresh-3/node_modules/rollup/dist/shared/rollup.js:9794:23)
    at Module.setSource (/repos/voboda/fresh-3/node_modules/rollup/dist/shared/rollup.js:10242:19)
    at ModuleLoader.addModuleSource (/repos/voboda/fresh-3/node_modules/rollup/dist/shared/rollup.js:18525:20)
    at ModuleLoader.fetchModule (/repos/voboda/fresh-3/node_modules/rollup/dist/shared/rollup.js:18581:9)
    at async Promise.all (index 0)
    at ModuleLoader.fetchStaticDependencies (/repos/voboda/fresh-3/node_modules/rollup/dist/shared/rollup.js:18606:34)
    at async Promise.all (index 0)
    at ModuleLoader.fetchModule (/repos/voboda/fresh-3/node_modules/rollup/dist/shared/rollup.js:18583:9)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svelte-app@1.0.0 build: `rollup -c`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the svelte-app@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

5. Install the requested rollup plugin per [instructions](https://github.com/rollup/plugins/tree/master/packages/json)
`npm install @rollup/plugin-json --save-dev`
And modify rollup.config.js accordingly, adding:
```
import json from '@rollup/plugin-json';
```
and modifying the plugins section:
```
...
        plugins: [
                json(),
                svelte({
                        compilerOptions: {

...
```
And running `npm run build` again, you should see the following warning:
```> rollup -c


src/main.js → public/build/bundle.js...
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
node_modules/@supabase/supabase-js/dist/module/SupabaseClient.js
1: var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
                    ^
2:     function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
3:     return new (P || (P = Promise))(function (resolve, reject) {
...and 1 other occurrence
node_modules/@supabase/realtime-js/dist/module/RealtimeClient.js
1: var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
                    ^
2:     function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
3:     return new (P || (P = Promise))(function (resolve, reject) {
...and 1 other occurrence
node_modules/@supabase/gotrue-js/dist/module/GoTrueApi.js
1: var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
                    ^
2:     function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
3:     return new (P || (P = Promise))(function (resolve, reject) {
...and 1 other occurrence

...and 3 other files
created public/build/bundle.js in 1s

```

## Expected behavior

As a novice developer, it's alarming to see these warnings -- I'm not sure if they're significant.

In a more complex application, these warning messages are repeated many more times, cluttering the output of `npm run dev`  on each rebuild.  How can this be resolved so the warnings don't occur?

## Notes

Having searched a little, I found some notes referring to `this.__awaiter` as a Typescript helper for earlier ES versions that don't have async/await.  These lines seem to be from the GoTrue packages.  Might this have something to do with combining various ES versions in rollup?

I also noticed that I don't get this problem when using snowpack and svelte, so this seems to be isolated to sapper or rollup.  

This is getting beyond my level of understanding of JS versions and build tools, but I thought it might be worth reporting here, since Sapper and Supabase are such complimentary combo. 

### System information

- Manjaro Linux (Arch-based)
- Node 15.6.0

package.json:
```
{
  "name": "svelte-app",
  "version": "1.0.0",
  "scripts": {
    "build": "rollup -c",
    "dev": "rollup -c -w",
    "start": "sirv public"
  },
  "devDependencies": {
    "@rollup/plugin-commonjs": "^17.0.0",
    "@rollup/plugin-json": "^4.1.0",
    "@rollup/plugin-node-resolve": "^11.0.0",
    "rollup": "^2.3.4",
    "rollup-plugin-css-only": "^3.1.0",
    "rollup-plugin-livereload": "^2.0.0",
    "rollup-plugin-svelte": "^7.0.0",
    "rollup-plugin-terser": "^7.0.0",
    "svelte": "^3.0.0"
  },
  "dependencies": {
    "@supabase/supabase-js": "^1.3.2",
    "sirv-cli": "^1.0.0"
  }
}```

Thanks!

**Comment by voboda** [comment]
I've found a solution.  It's to add `context: 'window',` to rolllup.config.js, as follows:

```
export default {
	client: {
		input: config.client.input(),
		context: 'window', 
```

**Comment by asafamr** [comment]
Solution didn't work for me, Svelte typescript starter, @supabase/supabase-js 1.20.0.
"websocket" 1.0.34 package requires its package.json for version in browser version. 
fixed by just adding @rollup/plugin-json rollup plugin as documented in https://www.npmjs.com/package/@rollup/plugin-json

**Comment by zakaria-chahboun** [comment]
For Svelte + Rollup, Just add `json` plugin

```npm
npm i @rollup/plugin-json
```
Add it into `rollup.configs.js`
```js
import json from '@rollup/plugin-json';
```
Go to plugins array and add this:
```js
plugins: [
		json(),
]
```

**Comment by DragoSpiro98** [comment]
> 

it doesn't solve the problem
