### ISSUE TITLE
Can't insantiate Supabase client; fails with GoTrue error "window is not defined."

### ISSUE THREAD

**Issue by Stokestack** [supabase/supabase-js#1249]
# Bug report

- [x ] I confirm this is a bug with Supabase, not with my own application. 
- [x ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com).

There is a similar-sounding and possibly related bug here: https://github.com/supabase/supabase-js/issues/786
But the workaround appears to be React-specific and doesn't seem to address the underlying problem.

## Describe the bug
I wrote a Deno-based server that is attempting to use Supabase. Upon attempting to insantiate the Supabase client, the application stops with an assertion thrown from GoTrueClient.js, _isImplicitGrantFlow():

In GoTrueClient.js, _isImplicitGrantFlow()
```
Exception has occurred: ReferenceError: window is not defined
  at SupabaseAuthClient._isImplicitGrantFlow (file:///Users/stokestack/Library/Caches/deno/npm/registry.npmjs.org/@supabase/auth-js/2.64.2/dist/main/GoTrueClient.js:1138:62)
    at SupabaseAuthClient._initialize (file:///Users/stokestack/Library/Caches/deno/npm/registry.npmjs.org/@supabase/auth-js/2.64.2/dist/main/GoTrueClient.js:170:64)
    at file:///Users/stokestack/Library/Caches/deno/npm/registry.npmjs.org/@supabase/auth-js/2.64.2/dist/main/GoTrueClient.js:155:35
    at file:///Users/stokestack/Library/Caches/deno/npm/registry.npmjs.org/@supabase/auth-js/2.64.2/dist/main/GoTrueClient.js:749:36
    at SupabaseAuthClient.lockNoOp [as lock] (file:///Users/stokestack/Library/Caches/deno/npm/registry.npmjs.org/@supabase/auth-js/2.64.2/dist/main/GoTrueClient.js:33:18)
    at SupabaseAuthClient._acquireLock (file:///Users/stokestack/Library/Caches/deno/npm/registry.npmjs.org/@supabase/auth-js/2.64.2/dist/main/GoTrueClient.js:745:31)
    at file:///Users/stokestack/Library/Caches/deno/npm/registry.npmjs.org/@supabase/auth-js/2.64.2/dist/main/GoTrueClient.js:154:31
    at SupabaseAuthClient.initialize (file:///Users/stokestack/Library/Caches/deno/npm/registry.npmjs.org/@supabase/auth-js/2.64.2/dist/main/GoTrueClient.js:157:11)
    at new GoTrueClient (file:///Users/stokestack/Library/Caches/deno/npm/registry.npmjs.org/@supabase/auth-js/2.64.2/dist/main/GoTrueClient.js:136:14)
    at new SupabaseAuthClient (https://jsr.io/@supabase/supabase-js/2.44.3/src/lib/SupabaseAuthClient.ts:6:5)
```
## To Reproduce

Set up a local-development environment for Supabase, and populate its public DB schema with a few tables. Run the Supabase TypeScript type generation on it and direct the output to DBTypes.ts in the source directory struture of any Deno project.

In that Deno project, try this:
```
import { createClient } from 'jsr:@supabase/supabase-js@2';
import { Database, Tables, Enums, TablesInsert, TablesUpdate } from './DBTypes.ts';

export const supabase = createClient<Database>('http://localhost:54321', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0')
```

## Expected behavior
The client is created and I can start executing queries with it.

## Screenshots
<img width="731" alt="Screenshot 2024-07-20 at 2 34 39 PM" src="https://github.com/user-attachments/assets/612d3eab-cd85-4c5a-800e-844def8a389e">

## System information

- OS: [e.g. macOS, Windows]
Mac OS version 14.5

- Browser (if applies) [e.g. chrome, safari]
N.A.

- Version of supabase-js: [e.g. 6.0.2]
I guess version 2, based on the import statement I'm using.

- Version of Node.js: [e.g. 10.10.0]
N.A.

## Additional context
Obviously this is a show-stopper.

**Comment by j4w8n** [comment]
Looks like this got resolved on Discord:

I'm not familiar with how you're using Deno, but if you add this option to your client, you shouldn't see the error. It's implying that you aren't doing implicit auth (and maybe you don't need auth anyway), and therefore won't call the _isImplictGrantFlow code.
```js
const supabase = createClient(url, key, {
  auth: {
    detectSessionInUrl: false
  }
})
```

**Comment by Stokestack** [comment]
Thanks. I wouldn't say it's resolved, though, because this method isn't documented (as far as I've seen). If you invoke the client as documented, it fails.
