### ISSUE TITLE
error TypeError: Cannot read property 'getItem' of undefined

### ISSUE THREAD

**Issue by salemalem** [supabase/supabase-js#167]
# Bug report
error TypeError: Cannot read property 'getItem' of undefined

## Description
When I run Deno JS it gives me this error:
error TypeError: Cannot read property 'getItem' of undefined
at y.getItem (https://unpkg.com/@supabase/supabase-js@1.11.9/dist/umd/supabase.js:1:3822)
    at n._recoverSession (https://unpkg.com/@supabase/supabase-js@1.11.9/dist/umd/supabase.js:1:13862)
    at new w (https://unpkg.com/@supabase/supabase-js@1.11.9/dist/umd/supabase.js:1:9242)
    at new n (https://unpkg.com/@supabase/supabase-js@1.11.9/dist/umd/supabase.js:1:53270)
    at t.default._initSupabaseAuthClient (https://unpkg.com/@supabase/supabase-js@1.11.9/dist/umd/supabase.js:1:51187)
    at new t.default (https://unpkg.com/@supabase/supabase-js@1.11.9/dist/umd/supabase.js:1:50233)
    at Object.t.createClient (https://unpkg.com/@supabase/supabase-js@1.11.9/dist/umd/supabase.js:1:53083)
    at file:///C:/Users/server.js:8:30 # replaced my file name
    at <anonymous> (<anonymous>)
TypeError: Cannot read property 'getItem' of undefined
    at y.getItem (https://unpkg.com/@supabase/supabase-js@1.11.9/dist/umd/supabase.js:1:3822)
    at n.<anonymous> (https://unpkg.com/@supabase/supabase-js@1.11.9/dist/umd/supabase.js:1:14223)
    at Generator.next (<anonymous>)
    at https://unpkg.com/@supabase/supabase-js@1.11.9/dist/umd/supabase.js:1:8543
    at new Promise (<anonymous>)
    at b (https://unpkg.com/@supabase/supabase-js@1.11.9/dist/umd/supabase.js:1:8288)
    at n._recoverAndRefresh (https://unpkg.com/@supabase/supabase-js@1.11.9/dist/umd/supabase.js:1:14147)
    at new w (https://unpkg.com/@supabase/supabase-js@1.11.9/dist/umd/supabase.js:1:9265)
    at new n (https://unpkg.com/@supabase/supabase-js@1.11.9/dist/umd/supabase.js:1:53270)
    at t.default._initSupabaseAuthClient (https://unpkg.com/@supabase/supabase-js@1.11.9/dist/umd/supabase.js:1:51187)
Error getting session from URL.

## To Reproduce

1. Install Deno JS
2. import "https://unpkg.com/@supabase/supabase-js";
3. const SERVICE_KEY = 'your-key';
const SUPABASE_URL = "https://xyz.supabase.co"
4. deno run --allow-net server.js
5. See error

Even though it shows an error, everything works well anyway. Is this a warning message then?

## Expected behavior

Everything should have worked without errors.

## Screenshots

![image](https://user-images.githubusercontent.com/42411937/117116452-3598fc80-adb0-11eb-8c22-31f83cb5913b.png)
![image](https://user-images.githubusercontent.com/42411937/117116676-755fe400-adb0-11eb-84a9-1c55346307f7.png)

## System information

- OS: Windows 10
- Browser: Brave
- Version of supabase-js: 1.11.9
- Version of Deno JS: 1.5.3

**Comment by salemalem** [comment]
insert function doesn't work on Deno JS

**Comment by kiwicopple** [comment]
Yeah this one is a Deno issue - we're tracking it here! 

https://github.com/supabase/supabase-js/issues/161

Will close in favour of the earlier issue
