### ISSUE TITLE
issue in cross-fetch while using cloudflare-workers and sveltekit 

### ISSUE THREAD

**Issue by bhvngt** [supabase/supabase-js#200]
# Bug report

## Describe the bug
I am trying to use cloudflare-workers, sveltekit and supabase. My local sveltkit build works without any issue. However, when I do `wrangler dev` or `wrangler publish`, I get following error after the build is successful. Looks like its throwing error while running on cloudflare environment. 

```
Uncaught
ReferenceError: require is not defined
    at node_modules/.pnpm/node-fetch@2.6.1/node_modules/node-fetch/lib/index.js (worker.js:59:18)
    at __require (worker.js:9:44)
    at node_modules/.pnpm/cross-fetch@3.0.6/node_modules/cross-fetch/dist/node-ponyfill.js (worker.js:1099:21)
    at __require (worker.js:9:44)
    at node_modules/.pnpm/@supabase+gotrue-js@1.16.2/node_modules/@supabase/gotrue-js/dist/main/lib/fetch.js (worker.js:1152:41)
    at __require (worker.js:9:44)
    at node_modules/.pnpm/@supabase+gotrue-js@1.16.2/node_modules/@supabase/gotrue-js/dist/main/GoTrueApi.js (worker.js:1442:19)
    at __require (worker.js:9:44)
    at node_modules/.pnpm/@supabase+gotrue-js@1.16.2/node_modules/@supabase/gotrue-js/dist/main/index.js (worker.js:2149:39)
    at __require (worker.js:9:44)
Uncaught (in response)
```

This could be related to #161. 

I tried by applying [cloudflare-worker-example](https://github.com/supabase/supabase/tree/master/examples/with-cloudflare-workers) patch. That does not seem to work on this.

Any workaround will be highly appreciated as we are sort of hitting a wall with this this.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. pnpm init svelte@next my-app
2. pnpx svelte-add joshnuss/svelte-supabase
3. wrangler init --site workers-site
4. configure wrangler.toml as follows
```
[site]
bucket = "./build"
entry-point = "workers-site"

[build]
command = "pnpm install && pnpm run build"

[build.upload]
format = "service-worker"
```
5. configure sveltekit to use @sveltejs/adapter-cloudflare-workers
6. wrangler build
7. wrangler dev throws above error

## Expected behavior

wrangler dev/publish to work

## System information

- OS: maxOS
- Version of supabase-js: 1.8.0
- Version of Node.js: 16.3

**Comment by bhvngt** [comment]
Since this issue is with Cloudflare-adapter that is part of sveltejs kit. I am closing this issue. Mirror details can be found [here](https://github.com/sveltejs/kit/issues/1674).
