### ISSUE TITLE
request to https://....supabase.c…&limit=31 failed, reason: certificate has expired

### ISSUE THREAD

**Issue by putheng** [supabase/supabase-js#283]
# Bug report
certificate has expired
## Describe the bug
I create a desktop app with ElectronJs but recently just got an error certificate has expired and cannot load the data

## System information

- OS:macOS
- Browser "electron": "12.0.6",
- Version of supabase-js: "@supabase/supabase-js": "^1.23.0",
- Version of Node.js: v14.17.2

```
code: "CERT_HAS_EXPIRED"
errno: "CERT_HAS_EXPIRED"
message: "request to https://..supabase.co/rest/v1/orders?select=*&order=id.desc.nullslast&offset=0&limit=31 failed, reason: certificate has expired"
type: "system"
stack: "FetchError: request to https://....supabase.co/rest/v1/orders?select=*&order=id.desc.nullslast&offset=0&limit=31 failed, reason: certificate has expired
at ClientRequest.<anonymous> (/node_modules/cross-fetch/node_modules/node-fetch/lib/index.js:1461:11)
at ClientRequest.emit (events.js:315:20)
at TLSSocket.socketErrorListener (_http_client.js:469:9)
at TLSSocket.emit (events.js:315:20)
at emitErrorNT (internal/streams/destroy.js:106:8)
at emitErrorCloseNT (internal/streams/destroy.js:74:3)
at processTicksAndRejections (internal/process/task_queues.js:80:21)"
__proto__: Error
```

**Comment by bnjmnt4n** [comment]
Bumping your electron version will likely fix this. Likely to do with Let’s Encrypt root certificate expiring: see https://github.com/electron/electron/issues/31212.

**Comment by soedirgo** [comment]
Closing due to inactivity.
