### ISSUE TITLE
App embedded in iframe, can't read localStorage (`_initSupabaseAuthClient`)

### ISSUE THREAD

**Issue by baptisteArno** [supabase/supabase-js#284]
# Bug report

## Describe the bug

Whenever my app is embedded and is executed on a browser that blocks 3rd party cookies (Chrome incognito mode), it crashes

```
DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at new constructor (https://bot.typebot.io/_next/static/chunks/232-9f427f032e260c4f70bf.js:1:20791)
    at new S (https://bot.typebot.io/_next/static/chunks/232-9f427f032e260c4f70bf.js:1:29809)
    at we._initSupabaseAuthClient (https://bot.typebot.io/_next/static/chunks/232-9f427f032e260c4f70bf.js:1:60282)
    at new we (https://bot.typebot.io/_next/static/chunks/232-9f427f032e260c4f70bf.js:1:59220)
    at Oe (https://bot.typebot.io/_next/static/chunks/232-9f427f032e260c4f70bf.js:1:61094)
    at Object.5947 (https://bot.typebot.io/_next/static/chunks/947-a52178cb2719aea458b0.js:1:4590)
    at n (https://bot.typebot.io/_next/static/chunks/webpack-e461b879a7fb8d69f062.js:1:149)
    at Module.7128 (https://bot.typebot.io/_next/static/chunks/pages/%5B...chatbotId%5D-fa008afff595c45cbca3.js:1:149)
    at n (https://bot.typebot.io/_next/static/chunks/webpack-e461b879a7fb8d69f062.js:1:149)
    at https://bot.typebot.io/_next/static/chunks/pages/%5B...chatbotId%5D-fa008afff595c45cbca3.js:1:410
    at https://bot.typebot.io/_next/static/chunks/main-3c04b02f8772d9f13a78.js:1:18402
```

I'm not sure where it throws exactly (I'm not authenticating, I just read the database). But the stacktrace indicates this function: `_initSupabaseAuthClient`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Open Chrome in Incognito mode and enable "Block third party cookies"
2. Run the app that uses Supabase in an iframe
3. See error

**Comment by baptisteArno** [comment]
I submitted an issue in the gotrue repo: https://github.com/supabase/gotrue-js/issues/148
