### ISSUE TITLE
The User object is null in Edge Function runtime with a valid authorization token

### ISSUE THREAD

**Issue by browasaki** [supabase/supabase-js#521]
# Bug report
The user object is null in Edge Function runtime with a valid authorization token.

## Describe the bug
I'm trying to get the User object with a valid Authorization token to perform an insert on a specific table that contains the user id; the user object is always at runtime, even with a valid authorization token.

## To Reproduce
- Create an Edge function and deploy it

```
// Get the authorization header from the request.
const authHeader = req.headers.get('Authorization').replace("Bearer ","")
// Client now respects auth policies for this user
supabaseClient.auth.setAuth(authHeader)
// set the user profile
const user = supabase.auth.user()

console.log(user);
>> null
```

## Expected behavior
Returns the current Auth user with UUID.

**Comment by Qw4z1** [comment]
Getting the same result from copy pasting sample code from the RESTful service.

Function call runs, but the user object is null and I can't access the database with my supabase client (assuming RLS blocks queries because the user is not authenticated).

```
myfunction/index.ts

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.33.2";

serve(async (req) => {
  const { url, method } = req;

  try {
    const supabaseClient = createClient(
      // Supabase API URL - env var exported by default.
      Deno.env.get("SUPABASE_URL") ?? "",
      // Supabase API ANON KEY - env var exported by default.
      Deno.env.get("SUPABASE_ANON_KEY") ?? "",
      // Create client with Auth context of the user that called the function.
      // This way your row-level-security (RLS) policies are applied.
      {
        global: {
          headers: { Authorization: req.headers.get("Authorization")! },
        },
      }
    );

    const {
      data: { user },
    } = await supabaseClient.auth.getUser();

    // Null here
    console.log("USER : ", user);

    return new Response(JSON.stringify({ user: user }), {
      headers: { "Content-Type": "application/json" },
      status: 200,
    });
  } catch (error) {
    return new Response(JSON.stringify({ error: error.message }), {
      headers: { "Content-Type": "application/json" },
      status: 400,
    });
  }
});
```

Sample node app:

```
import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  'LOCAL HOST',
  'SUPABASE_PUBLIC_KEY'
)


const { data: userData, error: userError } = await supabase.auth.signInWithPassword({
  email: 'my@email.com',
  password: 'mypassword',
})

// Exists here
console.log("User Data: ", userData)

const { data, error } = await supabase.functions.invoke('myfunction')
```

**Comment by Qw4z1** [comment]
Or maybe this is the issue... =/

> No storage option exists to persist the session, which may result in unexpected behavior when using auth.
> If you want to set persistSession to true, please provide a storage option or you may set persistSession to false to disable this warning.

**Comment by agtseito** [comment]
> Hi everyone, we have a guide here on how to set up the auth context in your edge function correctly: https://supabase.com/docs/guides/functions/auth#auth-context
> 
> @Qw4z1 are you still facing this issue? You need to set `persistSession` to false when you create the client in your sample node app
> 
> As for your code in your edge function, did you check if `req.headers.get("Authorization")` returns a user's JWT? You should also be setting `persistSession` to false when you create the client here.

Followed the guide, verified auth header returns JWT, set persistSession to false. Still getting null when calling getUser() and the missing sub claim error

```
// Create a Supabase client with the Auth context of the logged in user.
    const supabaseClient = createClient<Database>(
      // Supabase API URL - env var exported by default.
      Deno.env.get("SUPABASE_URL") ?? "",
      // Supabase API ANON KEY - env var exported by default.
      Deno.env.get("SUPABASE_ANON_KEY") ?? "",
      // Create client with Auth context of the user that called the function.
      // This way your row-level-security (RLS) policies are applied.
      {
        global: {
          headers: { Authorization: req.headers.get("Authorization")! },
        },
        auth: {
          persistSession: false,
        },
      },
    );
    const { data: { user }, error } = await supabaseClient.auth.getUser();
    console.log(user, error); // returns null
```

The error
```
[Info] null AuthApiError: invalid claim: missing sub claim
    at le (https://esm.sh/v135/@supabase/gotrue-js@2.57.0/esnext/gotrue-js.mjs:2:5282)
    at eventLoopTick (ext:core/01_core.js:64:7)
    at async Ie (https://esm.sh/v135/@supabase/gotrue-js@2.57.0/esnext/gotrue-js.mjs:2:6069)
    at async h (https://esm.sh/v135/@supabase/gotrue-js@2.57.0/esnext/gotrue-js.mjs:2:5806)
    at async https://esm.sh/v135/@supabase/gotrue-js@2.57.0/esnext/gotrue-js.mjs:2:26219
    at async m._useSession (https://esm.sh/v135/@supabase/gotrue-js@2.57.0/esnext/gotrue-js.mjs:2:25008)
    at async m._getUser (https://esm.sh/v135/@supabase/gotrue-js@2.57.0/esnext/gotrue-js.mjs:2:26136)
    at async https://esm.sh/v135/@supabase/gotrue-js@2.57.0/esnext/gotrue-js.mjs:2:25999
    at async https://esm.sh/v135/@supabase/gotrue-js@2.57.0/esnext/gotrue-js.mjs:2:24294 {
  __isAuthError: true,
  name: "AuthApiError",
  status: 401
}
```

**Comment by Chipsnet** [comment]
I am having the same error, but was able to get the user as follows

```ts
  const supabaseClient = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_ANON_KEY") ?? "",
    {
      global: {
        headers: { Authorization: req.headers.get("Authorization") ?? "" },
      },
    },
  );

  const jwt = req.headers.get("Authorization")!.split(" ")[1];
  const { data: { user }, error } = await supabaseClient.auth.getUser(jwt);
```

However, this is a different behavior from the documentation and this issue should be corrected

**Comment by filippovd20** [comment]
@Chipsnet thanks for figuring it out! In fact, the current behavior is correct and you have to pass the JWT token to ```getUser```.
It's documentation says "Gets the current user details if there is an existing session.". Apparently, there's no session in the edge environment so it's required.  Edge docs have to be fixed though.

**Comment by mattaylor** [comment]
This is super annoying and is a recent breaking change which has had serious consequences on our production services. Please FIX DOCS ASAP!

**Comment by mattaylor** [comment]
Setting authorization headers on new clients does not work as documented. The only solution to using clients within edge function is the undocumented solution identified by @Chipsnet

**Comment by SquareGraph** [comment]
Hey guys, any update on this issue?

I tested everything above + [https://github.com/supabase/supabase/blob/master/examples/edge-functions/supabase/functions/select-from-table-with-auth-rls/index.ts](url), but still getting null user.

What I'm trying to do is to trigger webhook with Edge Function, to update table based on any operation in another table.

**Comment by just-dodo** [comment]
any update on this issue?

**Comment by wadeowenwatt** [comment]
Any update on this ?

**Comment by bmoelk** [comment]
I'm getting `AuthApiError`'s even when passing the user's JWT into `getUser()`. 

IMO, this is a terrible bug as it seems the only viable workaround is to use the `service_role` key internally without validating the client's JWT. This circumvents the entire security system.

**Comment by Noahkoole** [comment]
Also breaking for me now. This needs to be fixed asap

**Comment by mandarini** [comment]
We have made a number of improvements on that front. Is this still an issue @bmoelk @Noahkoole ? Can you please provide a small reproduction so that I can debug this? Thank you all very much for your patience.

**Comment by mandarini** [comment]
Hi all! Coming back to this with an update. I want to confirm the state of things in case anyone lands here from search.

The original report on this thread used the v1 API (`supabaseClient.auth.setAuth` and `supabase.auth.user()`), which was replaced when supabase-js v2 shipped. The supported pattern in v2 is to pass the user's JWT through `global.headers.Authorization` when creating the client, and then call `await supabase.auth.getUser()`.

There was a real bug in the path between that pattern and `getUser()`: the auth client was returning `AuthSessionMissingError` (or `null`) when the only credential was a custom Authorization header, because it only looked at the local session for the access token. That behavior was fixed in [auth-js#891](https://github.com/supabase/auth-js/pull/891) (released in `@supabase/auth-js` 2.64.x) and properly wired up on the supabase-js side in #1029. Since then, the auth client tracks a `hasCustomAuthorizationHeader` flag and forwards the request to `/user` using your custom header when there is no local session.

I verified the current code path:

```ts
// supabase-js v2 inside an Edge Function
const supabaseClient = createClient(
  Deno.env.get('SUPABASE_URL') ?? '',
  Deno.env.get('SUPABASE_ANON_KEY') ?? '',
  {
    global: {
      headers: { Authorization: req.headers.get('Authorization')! },
    },
  }
)

const { data: { user }, error } = await supabaseClient.auth.getUser()
// user is populated, error is null, as long as the Authorization header is a real user JWT
```

A few notes on the follow-up reports in this thread:

- The `invalid claim: missing sub claim` errors that some folks hit are not the same bug. That message means the JWT being forwarded does not have a `sub` claim, which usually points to the anon key or service role key being sent in the Authorization header instead of an end user's access token. Double check that `req.headers.get('Authorization')` is the user's session JWT from the browser, not a project key.
- Passing the JWT explicitly to `getUser(jwt)` still works and is a fine pattern when you want to validate a token without involving the local session at all.
- The Edge Functions auth context guide is here: https://supabase.com/docs/guides/functions/auth#auth-context

I am going to close this since the underlying SDK bug has been resolved and we have not had a fresh reproduction since the fix shipped. If you are on a recent supabase-js version and still seeing `null` user with a real user JWT in the Authorization header, please open a new issue with a minimal reproduction (the JWT payload shape and the package versions you are running) and we will dig in.

Thanks again for the patience on this thread, everyone.
