### ISSUE TITLE
Image upload returns 500 with resumable uploads enabled

### ISSUE THREAD

**Issue by drewbietron** [supabase/supabase-js#755]
Our account was enabled for resumable uploads and we're now getting a 500 error when trying to upload images to Storage.

Error from logs
```json
"rawError": "{\"_error\":{\"name\":\"KnexTimeoutError\"},\"name\":\"KnexTimeoutError\",\"message\":\"Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?\",\"stack\":\"KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?\\n    at Client_PG.acquireConnection (/app/node_modules/knex/lib/client.js:312:26)\\n    at runNextTicks (node:internal/process/task_queues:60:5)\\n    at listOnTimeout (node:internal/timers:538:9)\\n    at process.processTimers (node:internal/timers:512:7)\\n    at async Transaction_PG.acquireConnection (/app/node_modules/knex/lib/execution/transaction.js:250:28)\"}",
```

This happened after asking to be enabled in the resumable uploads beta but it appears as if theres a breaking change for existing uploads?

We're on Supabase 2.10.0 but have tried updating the JS client but still with no luck.

**Comment by drewbietron** [comment]
Posted in the main repo

**Comment by RealmX1** [comment]
Wait how was this resolved?
