### ISSUE TITLE
Can't build sveltekit app with supabase.js using docker

### ISSUE THREAD

**Issue by MonsieurLazar** [supabase/supabase-js#771]
## Describe the bug

I have a simple sveltekit application with supabase.js. I use the client library listen to som e realtime data.

This is my Dockerfile:
FROM node:alpine

RUN apk update && apk add python3
RUN apk add py3-pip

COPY ./app/package.json .
COPY ./app/package-lock.json .
WORKDIR .
RUN npm install

COPY ./app/ ./

WORKDIR .
RUN npm run build
ENV BODY_SIZE_LIMIT 0
ENV PORT 80
EXPOSE 80
CMD ["node", "build"]

I get this error from github actions:
#10 [ 6/10] RUN npm install
#10 13.83 npm notice 
#10 13.83 npm notice New patch version of npm available! 9.6.4 -> 9.6.6
#10 13.83 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.6>
#10 13.83 npm notice Run `npm install -g npm@9.6.6` to update!
#10 13.83 npm notice 
#10 13.84 npm ERR! code 1
#10 13.84 npm ERR! path /node_modules/utf-8-validate
#10 13.85 npm ERR! command failed
#10 13.85 npm ERR! command sh -c node-gyp-build
#10 13.85 npm ERR! gyp info it worked if it ends with ok
#10 13.85 npm ERR! gyp info using node-gyp@9.3.1
#10 13.85 npm ERR! gyp info using node@20.1.0 | linux | arm64
#10 13.85 npm ERR! gyp info find Python using Python version 3.10.11 found at "/usr/bin/python3"
#10 13.85 npm ERR! gyp http GET https://nodejs.org/download/release/v20.1.0/node-v20.1.0-headers.tar.gz
#10 13.85 npm ERR! gyp http 200 https://nodejs.org/download/release/v20.1.0/node-v20.1.0-headers.tar.gz
#10 13.85 npm ERR! gyp http GET https://nodejs.org/download/release/v20.1.0/SHASUMS256.txt
#10 13.85 npm ERR! gyp http 200 https://nodejs.org/download/release/v20.1.0/SHASUMS256.txt
#10 13.85 npm ERR! gyp info spawn /usr/bin/python3
#10 13.85 npm ERR! gyp info spawn args [
#10 13.85 npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
#10 13.85 npm ERR! gyp info spawn args   'binding.gyp',
#10 13.85 npm ERR! gyp info spawn args   '-f',
#10 13.85 npm ERR! gyp info spawn args   'make',
#10 13.85 npm ERR! gyp info spawn args   '-I',
#10 13.85 npm ERR! gyp info spawn args   '/node_modules/utf-8-validate/build/config.gypi',
#10 13.85 npm ERR! gyp info spawn args   '-I',
#10 13.85 npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
#10 13.85 npm ERR! gyp info spawn args   '-I',
#10 13.85 npm ERR! gyp info spawn args   '/root/.cache/node-gyp/20.1.0/include/node/common.gypi',
#10 13.85 npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
#10 13.85 npm ERR! gyp info spawn args   '-Dvisibility=default',
#10 13.85 npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/20.1.0',
#10 13.85 npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
#10 13.85 npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/20.1.0/<(target_arch)/node.lib',
#10 13.85 npm ERR! gyp info spawn args   '-Dmodule_root_dir=/node_modules/utf-8-validate',
#10 13.85 npm ERR! gyp info spawn args   '-Dnode_engine=v8',
#10 13.85 npm ERR! gyp info spawn args   '--depth=.',
#10 13.85 npm ERR! gyp info spawn args   '--no-parallel',
#10 13.85 npm ERR! gyp info spawn args   '--generator-output',
#10 13.85 npm ERR! gyp info spawn args   'build',
#10 13.85 npm ERR! gyp info spawn args   '-Goutput_dir=.'
#10 13.85 npm ERR! gyp info spawn args ]
#10 13.85 npm ERR! gyp ERR! build error 
#10 13.85 npm ERR! gyp ERR! stack Error: not found: make
#10 13.85 npm ERR! gyp ERR! stack     at getNotFoundError (/usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/which.js:10:17)
#10 13.85 npm ERR! gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/which.js:57:18
#10 13.85 npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
#10 13.85 npm ERR! gyp ERR! stack     at step (/usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/which.js:54:21)
#10 13.85 npm ERR! gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/which.js:71:22
#10 13.85 npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
#10 13.85 npm ERR! gyp ERR! stack     at subStep (/usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/which.js:69:33)
#10 13.85 npm ERR! gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/which.js:80:22
#10 13.85 npm ERR! gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
#10 13.85 npm ERR! gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
#10 13.85 npm ERR! gyp ERR! System Linux 5.15.0-1034-oracle
#10 13.85 npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
#10 13.85 npm ERR! gyp ERR! cwd /node_modules/utf-8-validate
#10 13.85 npm ERR! gyp ERR! node -v v20.1.0
#10 13.85 npm ERR! gyp ERR! node-gyp -v v9.3.1
#10 13.85 npm ERR! gyp ERR! not ok
#10 13.86 
#10 13.86 npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-05-09T20_[35](https://github.com/lazarcloud/john-sensors/actions/runs/4930249067/jobs/8810917746#step:3:36)_50_916Z-debug-0.log
#10 ERROR: process "/bin/sh -c npm install" did not complete successfully: exit code: 1
------
 > [ 6/10] RUN npm install:
#10 13.85 npm ERR! gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:[42](https://github.com/lazarcloud/john-sensors/actions/runs/4930249067/jobs/8810917746#step:3:43):5
#10 13.85 npm ERR! gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
#10 13.85 npm ERR! gyp ERR! System Linux 5.15.0-1034-oracle
#10 13.85 npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
#10 13.85 npm ERR! gyp ERR! cwd /node_modules/utf-8-validate
#10 13.85 npm ERR! gyp ERR! node -v v20.1.0
#10 13.85 npm ERR! gyp ERR! node-gyp -v v9.3.1
#10 13.85 npm ERR! gyp ERR! not ok
#10 13.86 
#10 13.86 npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-05-09T20_35_[50](https://github.com/lazarcloud/john-sensors/actions/runs/4930249067/jobs/8810917746#step:3:51)_[91](https://github.com/lazarcloud/john-sensors/actions/runs/4930249067/jobs/8810917746#step:3:92)6Z-debug-0.log
------
Dockerfile:9
--------------------
   7 |     COPY ./app/package-lock.json .
   8 |     WORKDIR .
   9 | >>> RUN npm install
  10 |     
  11 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c npm install" did not complete successfully: exit code: 1
Error: Process completed with exit code 1.

I have also installed python because supabase-realtime is dependent on it.
## To Reproduce

Simply start a new sveltekit application and use the Dockerfile to build it.
Note that this bug applies only to the github worker, it succesfully compiles on my local machine. I believe there might be another dependency for supabase.js besides python.

## Expected behavior

To succesfully build the image.

## System information

- OS: ubuntu arm64
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by MonsieurLazar** [comment]
apparently you had to also install gcc

RUN apk add build-base
