### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'digest')

### ISSUE THREAD

**Issue by otang** [supabase/supabase-js#800]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

`supabase.auth.signUp` is throwing a difficult to debug error: "Cannot read properties of undefined (reading 'digest')". The error is new and has started occuring after upgrading my local supabase, installed via brew.

Is it due to accessing the app through a locally router domain name, eg. `myapp.local` as opposed to http://localhost:3000 ? It seems to work on localhost, but not when I have an entry in `/etc/hosts`: `127.0.0.1 myapp.local`

Stack:

```
client.js:1 TypeError: Cannot read properties of undefined (reading 'digest')
    at eval (helpers.js:229:1)
    at Generator.next (<anonymous>)
    at eval (helpers.js:7:1)
    at new Promise (<anonymous>)
    at __awaiter (helpers.js:3:1)
    at sha256 (helpers.js:226:1)
    at eval (helpers.js:245:1)
    at Generator.next (<anonymous>)
    at eval (helpers.js:7:1)
    at new Promise (<anonymous>)
    at __awaiter (helpers.js:3:1)
    at generatePKCEChallenge (helpers.js:240:1)
    at SupabaseAuthClient.eval (GoTrueClient.js:175:68)
    at Generator.next (<anonymous>)
    at fulfilled (GoTrueClient.js:4:43)
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Run the following on the latest version of locally running supabase:

```
      const { data } = await supabase.auth.signUp({
        email,
        password
      });
```

## Expected behavior

No error.

## Screenshots

![image](https://github.com/supabase/auth-helpers/assets/800081/bb1be990-e69c-4697-9645-51641909397f)

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by CarlosBalladares** [comment]
same issue here editing the hosts file.

Is there any workarounds?
