### ISSUE TITLE
TypeError: Illegal invocation

### ISSUE THREAD

**Issue by yunseop-dev** [supabase/supabase-js#830]
# Bug report
- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
When executing the `supabase.auth.signOut()` method, the following error message occurs.

```
Uncaught (in promise) TypeError: Illegal invocation
    at run (utils.js:41:9)
    at Array.forEach (<anonymous>)
    at run_all (utils.js:53:6)
    at destroy_component (Component.js:68:3)
    at root.svelte:44:41
    at transitions.js:89:5
    at run (utils.js:41:9)
    at Array.forEach (<anonymous>)
    at run_all (utils.js:53:6)
    at check_outros (transitions.js:57:3)
```

## To Reproduce

Call the `supabase.auth.signOut()` method.

## System information
- Version of supabase-js:: 2.32.0

**Comment by yunseop-dev** [comment]
sorry, it's my mistake...
