### ISSUE TITLE
fetch failed on Storage functions outside of browser

### ISSUE THREAD

**Issue by allpwrfulroot** [supabase/supabase-js#898]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Storage functions (download, list files) fail using local dev and an Express server. Other functions related to auth and Postgres seem to work fine. I've also tried switching from Node 18 to 20, no difference. 

Storage functions via browser work OK. 

```
const { data: pdfData, error } = await supabase.storage
      .from("example")
      .list("demo", {});
```

```
ai-server-ai_server-1    | [1] Error: StorageUnknownError: fetch failed
ai-server-ai_server-1    | [1]     at /app/node_modules/@supabase/storage-js/dist/main/lib/fetch.js:29:16
ai-server-ai_server-1    | [1]     at Generator.next (<anonymous>)
ai-server-ai_server-1    | [1]     at fulfilled (/app/node_modules/@supabase/storage-js/dist/main/lib/fetch.js:5:58)
ai-server-ai_server-1    | [1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
ai-server-ai_server-1    | [1]   __isStorageError: true,
ai-server-ai_server-1    | [1]   originalError: TypeError: fetch failed
ai-server-ai_server-1    | [1]       at Object.fetch (node:internal/deps/undici/undici:11372:11)
ai-server-ai_server-1    | [1]       at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
ai-server-ai_server-1    | [1]     cause: _ConnectTimeoutError: Connect Timeout Error
ai-server-ai_server-1    | [1]         at onConnectTimeout (node:internal/deps/undici/undici:6616:28)
ai-server-ai_server-1    | [1]         at node:internal/deps/undici/undici:6574:50
ai-server-ai_server-1    | [1]         at Immediate._onImmediate (node:internal/deps/undici/undici:6605:13)
ai-server-ai_server-1    | [1]         at process.processImmediate (node:internal/timers:478:21) {
ai-server-ai_server-1    | [1]       code: 'UND_ERR_CONNECT_TIMEOUT'
ai-server-ai_server-1    | [1]     }
ai-server-ai_server-1    | [1]   }
ai-server-ai_server-1    | [1] }
```

## To Reproduce

In a NodeJS environment, use Storage features:

```
const { data: pdfData, error } = await supabase.storage
      .from("example")
      .list("demo", {});
```

## Expected behavior

A returned list of file info.

## System information

- OS: MacOS
- Environment: ExpressJS
- Version of supabase-js: "2.38.4"
- Version of Node.js: 18, 20

## Additional context

Running the Express server within a docker compose setup w/ Redis, etc.

**Comment by mandarini** [comment]
I will be closing this issue since it has no activity for more than 2 years.

If you find that the issue persists on the latest version of our libs, feel free to open a new one, ideally with a small reproduction repository.

Thank you for your patience and for contributing to Supabase!
