### ISSUE TITLE
Error on exchangeCodeForSession when setting the token key for password recovery

### ISSUE THREAD

**Issue by JuanxCursed** [supabase/supabase-js#950]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I was trying to work on a more detailed workflow when recovering the password, and when I was taking a look at the source code, I've found a possible bug

When the recovery token is recorded into the storage, the key stored is `sb-api-auth-token-code-verifier` but when the code tries to `exchangeCodeForSession` at line 545, `${this.storageKey}-code-verifier`.
this.storageKey is a constant set into the `constants.ts` named `STORAGE_KEY` and its value is `supabase.auth.token`

Due to this, when `exchangeCodeForSession` is executed, since it doesn't find the `code-verifier`, I receive this error:

```
AuthApiError: invalid request: both auth code and code verifier should be non-empty
````

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Send a email password reset link
2. Check the storage key created
3. Click on the reset link
4. When redirect to your site with the code query string try to execute `exchangeCodeForSession` with this value
5. See the error on console

## Expected behavior

Recover the session to reset the password properly

## System information

- OS: macOS
- Browser (if applies) chrome
- Version of supabase-js:  2.39.3
- Version of @nuxtjs/supabase: 1.1.5
- Version of VueJs: 3.3.8
- Version of Node.js: 18.16.0

**Comment by Lenninlasd** [comment]
Same bug here, I got this error message:
```
AuthApiError: invalid request: both auth code and code verifier should be non-empty
    at handleError (/Users/.../node_modules/@supabase/auth-js/dist/main/lib/fetch.js:63:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _handleRequest (/Users/.../node_modules/@supabase/auth-js/dist/main/lib/fetch.js:111:9)
    at async _request (/Users/.../node_modules/@supabase/auth-js/dist/main/lib/fetch.js:89:18)
    at async SupabaseAuthClient._exchangeCodeForSession (/Users/.../node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:409:33)
    at async /Users.../node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:736:28 {
  __isAuthError: true,
  status: 400,
  code: undefined
```

**Comment by oyeesam** [comment]
I have followed this steps from the [docs](https://supabase.com/docs/guides/auth/social-login/auth-google?queryGroups=framework&framework=remix)

```ts
// sign-in.tsx
const { data, error } = await supabase.auth.signInWithOAuth({
			provider: "google",
			options: {
				redirectTo: "http://localhost:5173/auth/callback",
			},
		});

		if (data.url) {
			return redirect(data.url);
		}

```

On auth callback route

```ts
import { type LoaderFunctionArgs, redirect } from "@remix-run/cloudflare";
import { supabaseClient } from "~/services/supabase.server";

export async function loader({ request, context }: LoaderFunctionArgs) {
	const requestUrl = new URL(request.url);
	const code = requestUrl.searchParams.get("code");
	const next = requestUrl.searchParams.get("next") || "/";
	const headers = new Headers();

	console.log("code login\t", code);
	if (code) {
		const supabase = supabaseClient(request, context, headers);

		const { error } = await supabase.auth.exchangeCodeForSession(code);

		if (!error) {
			return redirect(next, { headers });
		}
	}

	// return the user to an error page with instructions
	return redirect("/auth/auth-code-error", { headers });
}

```

I am getting same error as

```
AuthApiError: invalid request: both auth code and code verifier should be non-empty
    at handleError (/home/hmlesam/FlashNDot/saralcms/dashboard/node_modules/.pnpm/@supabase+auth-js@2.64
.4/node_modules/@supabase/auth-js/dist/main/lib/fetch.js:63:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _handleRequest (/home/hmlesam/FlashNDot/saralcms/dashboard/node_modules/.pnpm/@supabase+aut
h-js@2.64.4/node_modules/@supabase/auth-js/dist/main/lib/fetch.js:108:9)
    at async _request (/home/hmlesam/FlashNDot/saralcms/dashboard/node_modules/.pnpm/@supabase+auth-js@2
.64.4/node_modules/@supabase/auth-js/dist/main/lib/fetch.js:89:18)
    at async SupabaseAuthClient._exchangeCodeForSession (/home/hmlesam/FlashNDot/saralcms/dashboard/node
_modules/.pnpm/@supabase+auth-js@2.64.4/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:408:33)
    at async /home/hmlesam/FlashNDot/saralcms/dashboard/node_modules/.pnpm/@supabase+auth-js@2.64.4/node
_modules/@supabase/auth-js/dist/main/GoTrueClient.js:719:28 

{
  __isAuthError: true,
  status: 400,
  code: 'validation_failed'
}
```


System Information:
OS: Fedora
Nodejs: 20.11.0
"@supabase/ssr": "^0.4.0",
"@supabase/supabase-js": "^2.45.0"
Framework Remix: 
"@remix-run/cloudflare": "^2.10.3",
"@remix-run/cloudflare-pages": "^2.10.3",
"@remix-run/react": "^2.10.3",

**Comment by Proziam** [comment]
This appears to be related to [#545](https://github.com/supabase/auth-helpers/issues/545)

I can confirm that this bug is happening to another project which uses svelte rather than react.

**Comment by marekf93** [comment]
Hi, anything new?

**Comment by kewur** [comment]
any work around?

**Comment by prototipal** [comment]
Same error


`{"code":"validation_failed","message":"invalid request: both auth code and code verifier should be non-empty"}`

**Comment by rtrigoso** [comment]
same error

**Comment by ethernetz** [comment]
same error...

**Comment by selvanram** [comment]
same error

**Comment by elvinjgalarza** [comment]
same

**Comment by benkissi** [comment]
Experiencing same issue

**Comment by Casmir293** [comment]
I'm getting this issue too.

After clicking on the link (via the reset password email), I get redirected to my set-password page (with the url having a query ?code='xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx').

I extract the code and insert it in here as instructed in the docs: 

`await supabase.auth.exchangeCodeForSession(code)`

and the network error response is:
```
{
    "code": "validation_failed",
    "message": "invalid request: both auth code and code verifier should be non-empty"
}
```

query string:
```
grant_type: pkce
```

and the payload:
```
{
    "auth_code": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "code_verifier": ""
}
```

Has anyone found their way around this yet?

**Comment by mandarini** [comment]
Thanks for the report. After investigating, there are a few things going on here:

**What's Happening**

This is a known limitation of PKCE flow, but the error message is unhelpful and the documentation doesn't make the limitation clear enough for common use cases. When you call `resetPasswordForEmail()` (or any PKCE-initiating method), a code verifier is stored locally. When the user clicks the email link and `exchangeCodeForSession()` is called, it needs to retrieve that code verifier from the same storage. The code verifier must be accessible from where `exchangeCodeForSession()` is called. This fails when:
1. User opens the email link in a different browser/device
2. User opens in incognito/private mode
3. SSR apps where server-side code can't access client-side `localStorage`
4. Different origins, like if your redirect URL has a different subdomain, `localStorage` isn't shared

**For SSR Frameworks (Nuxt, Next.js, SvelteKit, etc.)**

If you're using an SSR framework, you must use `@supabase/ssr` which stores the code verifier in cookies instead of `localStorage`. This is the recommended approach. For Nuxt specifically, `@nuxtjs/supabase` should be handling this, but you may need to ensure:
1. The Supabase client is properly configured with cookie storage
2. Cookies are being set/read correctly in your auth callback

**What We Could Improve**

Looking at the number of comments in this issue, I think we should improve the error message. Instead of the generic "both auth code and code verifier should be non-empty", we could say something  like: "Code verifier not found. This usually means the session was initiated in a different browser or the storage was cleared. For SSR apps, ensure you're using @supabase/ssr with cookie storage." Also, maybe the PKCE limitations should be more prominently documented, especially for password recovery flows.

**For anyone hitting this issue right now:**

  - Client-side apps: Ensure users open the email link in the same browser where they initiated the reset
  - SSR apps: Use `@supabase/ssr` package which handles cookie-based storage
  - Nuxt: Check that `@nuxtjs/supabase` is properly configured and up to date
  - Quick workaround: If PKCE isn't strictly required for your use case, you can use `flowType: 'implicit'` (the default)

**Comment by Casmir293** [comment]
I was able to get past this issue by including the user email in the redirectURL when submitting the email where the url should be sent.

,,,
const supabase = useSupabaseClient();
let email = "";

const submit = async () => {
  const { data, error } = await supabase.auth.resetPasswordForEmail(
    email,
    {
      redirectTo: `https://your-url/your-reset-password-path?email=${encodeURIComponent(email)}`,
    }
  );
  
  if (error) {
    console.log("Failed to send reset email. Please try again.", error);
  } else {
    console.log("Please check your email for the reset link");
  }
};
,,,

Then on the reset-password-path file I used the admin privilege to update the password (on the server)

```
// Use admin client
    const supabaseAdmin = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
      {
        auth: {
          autoRefreshToken: false,
          persistSession: false,
        },
      }
    );

    // Query users table to get user ID by email
    const { data: user, error: queryError } = await supabaseAdmin
      .from("users")
      .select("id, email")
      .eq("email", email.toLowerCase())
      .single();

    if (queryError || !user) {
      return new Response(JSON.stringify({ error: "User not found" }), {
        status: 404,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Update password using the user ID from profile
    const { error: updateError } = await supabaseAdmin.auth.admin.updateUserById(user.id, { password });

    if (updateError) {
      return new Response(JSON.stringify({ error: updateError.message }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    return new Response(JSON.stringify({ success: true, message: "Password updated successfully" }), {
      status: 200,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
```

This solved the issue regardless of the platform (web or mobile).

Thanks.
